version: '3'
services:
  camagru:
    image: camagru:latest
    environment:
      - PYTHONPATH=/home/camagru
    restart: always
    ports:
      - "8051:8051"
      - "8052:8052"
    volumes:
      - .:/home

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  nginx:
    image: nginx
    ports:
      - "8086:8086"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - .:/home