version: '3'
services:
  camagru:
    image: camagru:latest
    environment:
      - PYTHONPATH=/home/camagru
    restart: always
    ports: [8051:8051]
    volumes:
      - .:/home

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
