version: '3'
services:
  camagru:
    image: camagru:latest
    environment:
      - PYTHONPATH=/home/camagru
    restart: always
    ports: [8051:8051]
    volumes:
      - .:/home

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  apache:
    image: httpd
    ports:
      - "8080:80"
