[tool.poetry]
name = "camagru"
version = "0.1.0"
description = "Instagram-like application"
authors = ["Paul JULLIEN"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2-binary = "^2.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
